import Image from "next/image";

export const metadata = {
  title: "EcoVista ! Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  aqi,
  wind,
  temperature,
  weather,
}) {
  return (
    <div className="wrapper">
      <Image
        src="/background.png"
        className="bg-img"
        width={700}
        height={1200}
        alt="bg-image"
      />
      <div className="overlay"></div>
      <main className="!z-50 w-full">
        <div className="container">
          <div className="grid grid-cols-12 gap-y-8 py-16 lg:gap-8 2xl:gap-20 2xl:py-20">
            {children}
            {weather}
            {aqi}
            {wind}
            {temperature}
          </div>
        </div>
      </main>
    </div>
  );
}
